---
# defaults file for kubernetes

kubernetes_containerd_version: "1.7.27-0ubuntu1~22.04.1"

kubernetes_cluster_name: "demo"
kubernetes_major_version: "1.34"
kubernetes_minor_version: "1.34.1-1.1"
kubernetes_pod_network_cidr: "192.168.0.0/24"
kubernetes_control_plane_endpoint: "10.10.0.30"
kubernetes_default_network_interface: "eth1"

kubernetes_cilium_version: "1.17.8"

kubernetes_secrets:
  - name: digitalocean
    namespace: kube-system
    string_data:
      access-token: "{{ lookup('env', 'DO_API_TOKEN') }}"
      vpc-id: "{{ lookup('env', 'DO_CLUSTER_VPC_ID') }}"

kubernetes_manifests:
  - digitalocean-cloud-controller-manager.yaml
  - digitalocean-cloud-controller-manager-admission-server.yaml
  - letsencrypt.yaml

kubernetes_helm_charts:
  - name: cert-manager
    repo_name: jetstack
    repo_url: https://charts.jetstack.io
    chart: cert-manager
    namespace: cert-manager
    create_namespace: true
    version: v1.18.2
    values_file: cert-manager.yaml
  - name: nginx-ingress
    repo_name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    namespace: ingress-nginx
    create_namespace: true
    version: 4.12.6
    values_file: nginx-ingress.yaml
  - name: metrics-server
    repo_name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server
    chart: metrics-server
    namespace: metrics-server
    create_namespace: true
    version: 3.13.0
    values_file: metrics-server.yaml
