---
- name: Check if containerd is already installed
  ansible.builtin.stat:
    path: "/etc/containerd/config.toml"
  register: containerd_config_file

- name: Install and configure containerd
  when: not containerd_config_file.stat.exists
  block:
    - name: Install containerd package
      ansible.builtin.apt:
        name:
          - containerd={{ kubernetes_containerd_version }}
        state: present
        update_cache: true

    - name: Ensure /etc/containerd exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config if not exists
      ansible.builtin.command: containerd config default
      register: containerd_config
      changed_when: false

    - name: Save containerd config
      ansible.builtin.copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        mode: '0644'

    - name: Ensure containerd uses systemd cgroup driver
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Enable and restart containerd
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: restarted
